export const UPDATE_ITEM = 'UPDATE_ITEM';
export const SET_QUOTE_FROM_DEFINITION = 'SET_QUOTE_FROM_DEFINITION';
export const UPDATE_ENVIRONMENT = 'UPDATE_ENVIRONMENT';
export const INDEX_DEFINITIONS = 'INDEX_DEFINITIONS';
