export const UPDATE_ITEM = 'UPDATE_ITEM';
export const SET_QUOTE_FROM_DEFINITION = 'SET_QUOTE_FROM_DEFINITION';
export const UPDATE_ENVIRONMENT = 'UPDATE_ENVIRONMENT';
export const INDEX_DEFINITIONS = 'INDEX_DEFINITIONS';
export const SET_CONTACT = 'SET_CONTACT';
export const SEND_QUOTE = 'SEND_QUOTE';
export const SAVE_QUOTE = 'SAVE_QUOTE';
